[train_ONT_chemistry]
fdr=0.05
device=cpu
sup_lr=0.0001
semi_lr=0.0001
input_size=6
input_length=15
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=1
train_sample_fraction=0.4
val_sample=1
val_sample_fraction=0.25
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=30
semi_supervised_train_epochs=20
sup_train_data=../data/ml_data/HG002_2_3_00_train.npz
sup_val_data=../data/ml_data/HG002_2_3_00_val.npz
semi_train_data=../data/ml_data/HG002_2_3_00_train.npz
semi_val_data=../data/ml_data/HG002_2_3_00_val.npz
best_supervised_model_name=../models/m6A_ONT_supervised_cnn.best.torch.pickle
final_supervised_model_name=../models/m6A_ONT_supervised_cnn.final.torch
pretrain_model_name=../models/m6A_ONT_supervised_cnn.best.torch.pickle
best_semi_supervised_model_name=../models/m6A_ONT_semi_supervised_cnn.best.torch.pickle
final_semi_supervised_model_name=../models/m6A_ONT_semi_supervised_cnn.final.torch.pickle
save_pos=../results/semi_train_ONT_chemistry.npz
score_ap_json=../results/semi_ONT_score_precision.json
score_ap_table=../results/semi_ONT_score_precision.tsv